<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Gare;
use App\Models\LigneRer;

class GareSeeder extends Seeder
{
    public function run()
    {
        // La liste complète et vérifiée, avec renommage des doublons et tri alphabétique
        $allGaresData = [
            "A" => ["Auber", "Boissy-Saint-Léger", "Bry-sur-Marne", "Bussy-Saint-Georges", "Champigny", "Charles de Gaulle – Étoile", "Châtelet – Les Halles (A)", "Chatou – Croissy", "Fontenay-sous-Bois", "Gare de Lyon (A)", "Joinville-le-Pont", "La Défense (A)", "La Varenne – Chennevières", "Le Parc de Saint-Maur", "Le Vésinet – Centre", "Le Vésinet – Le Pecq", "Lognes", "Marne-la-Vallée – Chessy", "Nanterre-Préfecture", "Nanterre-Université (A)", "Nanterre-Ville", "Nation", "Nogent-sur-Marne", "Noisiel", "Noisy-Champs", "Noisy-le-Grand – Mont d’Est", "Rueil-Malmaison", "Saint-Germain-en-Laye", "Saint-Maur – Créteil", "Sucy – Bonneuil", "Torcy", "Val de Fontenay (A)", "Val d’Europe", "Vincennes"],
            "B" => ["Aéroport CDG 1", "Aéroport Charles de Gaulle 2", "Antony", "Arcueil - Cachan", "Aulnay-sous-Bois", "Bagneux", "Bourg-la-Reine", "Bures-sur-Yvette", "Châtelet - Les Halles (B)", "Cité Universitaire", "Courcelle-sur-Yvette", "Denfert-Rochereau", "Drancy", "Fontaine Michalon", "Gare du Nord (B)", "Gentilly", "Gif-sur-Yvette", "La Courneuve - Aubervilliers", "La Croix de Berny", "La Hacquinière", "La Plaine Stade de France", "Laplace", "Le Blanc-Mesnil", "Le Bourget", "Le Guichet", "Les Baconnets", "Lozère", "Luxembourg", "Massy - Palaiseau (B)", "Massy - Verrières (B)", "Mitry - Claye", "Orsay Ville", "Palaiseau", "Palaiseau - Villebon", "Parc de Sceaux", "Parc des Expositions", "Port Royal", "Robinson", "Saint-Michel Notre-Dame (B)", "Saint-Rémy-lès-Chevreuse", "Sevran Beaudottes", "Sevran - Livry", "Vert Galant", "Villeparisis - Mitry-le-Neuf", "Villepinte"],
            "C" => ["Ablon", "Angerville", "Arpajon", "Athis-Mons", "Avenue du Président Kennedy", "Avenue Foch", "Avenue Henri Martin", "Bibliothèque François Mitterrand", "Bièvres", "Boulainvilliers", "Bouray", "Boutervilliers – Bois-Herpin", "Brétigny", "Breuillet - Bruyères-le-Châtel", "Breuillet - Village", "Cernay", "Chamarande", "Champ de Mars – Tour Eiffel", "Chaville – Vélizy", "Chemin d'Antony", "Choisy-le-Roi", "Dourdan", "Dourdan – La Forêt", "Égly", "Épinay-sur-Orge", "Épinay-sur-Seine", "Ermont – Eaubonne (C)", "Étampes", "Étréchy", "Franconville – Le Plessis-Bouchard", "Gare d’Austerlitz", "Gennevilliers (C)", "Grand Bourg", "Grigny – Centre", "Igny", "Invalides", "Issy", "Issy – Val de Seine", "Ivry-sur-Seine", "Javel", "Jouy-en-Josas", "Juvisy (C)", "La Norville – Saint-Germain-lès-Arpajon", "Lardy", "Le Bras de Fer – Évry Génopole", "Les Ardoines", "Les Grésillons (C)", "Les Saules", "Marolles-en-Hurepoix", "Massy – Palaiseau (C)", "Massy – Verrières (C)", "Meudon-Val-Fleury", "Monnerville", "Montigny – Beauchamp", "Musée d’Orsay", "Neuilly – Porte Maillot", "Orangis – Bois de l’Épine", "Orly Ville", "Pereire – Levallois", "Petit Jouy – Les Loges", "Pierrelaye (C)", "Pont de l'Alma", "Pont de Rungis – Aéroport d’Orly", "Pontoise (C)", "Porchefontaine", "Porte de Clichy", "Ris-Orangis", "Rungis – La Fraternelle", "Saint-Chéron", "Sainte-Geneviève-des-Bois", "Saint-Gratien", "Saint-Martin-d'Étampes", "Saint-Michel – Notre-Dame (C)", "Saint-Michel-sur-Orge", "Saint-Ouen (C)", "Saint-Ouen-l’Aumône", "Saint-Ouen-l’Aumône – Liesse (C)", "Savigny-sur-Orge", "Sermaise", "Valenton", "Vauboyen", "Versailles – Chantiers (C)", "Versailles – Château – Rive Gauche", "Villeneuve-le-Roi", "Villeneuve-Saint-Georges", "Viroflay – Rive Gauche (C)", "Vitry-sur-Seine"],
            "D" => ["Boussy-Saint-Antoine", "Brunoy", "Buno - Gironville", "Chantilly - Gouvieux", "Châtelet - Les Halles (D)", "Combs-la-Ville - Quincy", "Corbeil-Essonnes", "Creil (D)", "Créteil - Pompadour", "Évry - Courcouronnes", "Gare de Lyon (D)", "Gare du Nord (D)", "Garges - Sarcelles", "Goussainville", "Grand-Bourg", "Grigny-Centre", "Juvisy (D)", "La Borne Blanche", "Le Bras-de-Fer - Évry-Génopole", "Le Mée", "Le Vert de Maisons", "Les Noues", "Lieusaint - Moissy", "Louvres", "Maisons-Alfort - Alfortville", "Malesherbes", "Melun", "Montgeron - Crosne", "Orangis - Bois de l’Épine", "Orry-la-Ville - Coye", "Pierrefitte - Stains", "Quincy - Sous-Sénart", "Ris-Orangis", "Saint-Denis (D)", "Savigny-le-Temple - Nandy", "Stade de France - Saint-Denis", "Survilliers - Fosses", "Vigneux-sur-Seine", "Villeneuve-Saint-Georges", "Villeneuve-Triage", "Villiers-le-Bel - Gonesse - Arnouville", "Yerres"],
            "E" => ["Bondy", "Chelles - Gournay", "Émerainville - Pontault-Combault", "Gagny", "Gretz-Armainvilliers", "Haussmann Saint-Lazare", "La Défense (E)", "Le Chénay Gagny", "Le Raincy - Villemomble - Montfermeil", "Les Boullereaux - Champigny", "Les Yvris Noisy-le-Grand", "Magenta", "Nanterre-La-Folie", "Neuilly Porte Mailot", "Nogent - Le Perreux", "Noisy-le-Sec", "Ozoir-la-Ferrière", "Pantin", "Roissy-en-Brie", "Rosa Parks", "Rosny Bois Perrier", "Rosny-sous-Bois", "Tournan", "Val de Fontenay (E)", "Villiers-sur-Marne - Le Plessis-Trévise"],
            "H" => ["Auvers-sur-Oise", "Belloy – Saint-Martin", "Bessancourt", "Boran-sur-Oise", "Bouffémont – Moisselles", "Bruyères-sur-Oise", "Cernay", "Champ de courses d’Enghien", "Champagne-sur-Oise", "Chaponval", "Creil (H)", "Deuil – Montmagny", "Domont", "Écouen – Ézanville", "Enghien-les-Bains", "Épinay – Villetaneuse", "Épluches", "Ermont – Eaubonne (H)", "Ermont‑Halte", "Franconville – Le Plessis‑Bouchard", "Frépillon (H)", "Groslay", "Gros Noyer – Saint‑Prix", "La Barre – Ormesson", "L’Isle‑Adam – Parmain", "Luzarches", "Méry-sur-Oise", "Mériel", "Montigny – Beauchamp (H)", "Montsoult – Maffliers", "Nointel – Mours", "Paris Nord (H)", "Persan – Beaumont (H)", "Pierrelaye (H)", "Pont‑Petit", "Pontoise (H)", "Précy-sur-Oise", "Presles – Courcelles", "Saint-Denis (H)", "Saint‑Leu‑d’Esserent", "Saint‑Leu‑la‑Forêt", "Saint‑Ouen‑l’Aumône (H)", "Saint‑Ouen‑l’Aumône – Liesse (H)", "Sarcelles – Saint‑Brice", "Seugy", "Taverny", "Valmondois", "Vaucelles", "Villaines"],
            "J" => ["Achères – Grand Cormier", "Achères – Ville", "Andrésy", "Argenteuil", "Asnières-sur-Seine (J)", "Aubergenville – Élisabethville", "Boissy-l’Aillerie", "Bois-Colombes", "Chanteloup-les-Vignes", "Chars", "Clichy – Levallois (J)", "Colombes", "Conflans – Sainte-Honorine", "Conflans-Fin-d’Oise (J)", "Cormeilles-en-Parisis", "Épône – Mézières", "Éragny – Neuville", "Ermont – Eaubonne (J)", "Frépillon (J)", "Gisors", "Herblay", "Houilles – Carrières-sur-Seine (J)", "Jouy-le-Moutier", "La Frette – Montigny", "La Garenne-Colombes (J)", "Lavilletertre", "Le Mesnil-le-Roi", "Le Pecq", "Le Stade (J)", "Les Clairières de Verneuil", "Les Mureaux", "Liancourt-Saint-Pierre", "Maisons-Laffitte (J)", "Mantes-la-Jolie (J)", "Mantes-Station", "Maurecourt", "Montigny – Beauchamp (J)", "Nanterre – Université (J)", "Neuville-Université (J)", "Paris Saint-Lazare (J)", "Pierrelaye (J)", "Poissy (J)", "Pont Cardinet (J)", "Pontoise (J)", "Saint-Germain-en-Laye Grande-Ceinture", "Saint-Ouen-l’Aumône (J)", "Saint-Ouen-l’Aumône – Liesse (J)", "Santeuil – Le Perchay", "Sartrouville (J)", "Triel-sur-Seine", "Trie-Château", "Us", "Val d’Argenteuil", "Vaux-sur-Seine", "Vernouillet‑Verneuil", "Villennes-sur-Seine"],
            "K" => ["Aulnay-sous-Bois", "Compans", "Crépy-en-Valois", "Dammartin - Juilly - Saint-Mard", "Gare du Nord (K)", "Le Plessis-Belleville", "Mitry - Claye (K)", "Nanteuil-le-Haudouin", "Paris Nord (K)", "Thieux - Nantouillet"],
            "L" => ["Asnières-sur-Seine (L)", "Bécon-les-Bruyères", "Bougival", "Chaville – Rive Droite (L)", "Clichy – Levallois (L)", "Courbevoie", "Garches – Marnes-la-Coquette", "La Celle-Saint-Cloud", "La Défense (L)", "La Garenne-Colombes (L)", "Le Stade (L)", "Le Val d’Or (L)", "Les Ternes", "Les Vallées", "L’Étang-la-Ville", "Louveciennes", "Marly-le-Roi", "Montreuil", "Nanterre – La Folie", "Nanterre – Université (L)", "Paris Saint-Lazare (L)", "Pereire", "Pont Cardinet (L)", "Puteaux (L)", "Saint-Cloud (L)", "Saint-Nom-la-Bretèche – Forêt de Marly", "Sèvres – Ville-d’Avray (L)", "Suresnes – Mont-Valérien (L)", "Vaucresson", "Versailles – Rive Droite", "Viroflay – Rive Droite (L)"],
            "N" => ["Aubergenville – Élisabethville", "Bellevue", "Chaville – Rive Gauche (N)", "Clamart", "Coignières", "Dreux", "Épône – Mézières", "Garancières – La Queue", "Houdan", "La Verrière (N)", "Le Perray", "Les Essarts-le-Roi", "Mantes-la-Jolie (N)", "Mantes-Station", "Marchezais – Broué", "Meudon", "Montfort-l’Amaury – Méré", "Nézel – Aulnay", "Orgerus – Bérou", "Paris-Montparnasse", "Plaisir – Grignon", "Plaisir – Les Clayes", "Rambouillet", "Saint-Cyr (N)", "Saint-Quentin-en-Yvelines – Montigny-le-Bretonneux", "Sèvres – Rive Gauche", "Tacoignières – Richebourg", "Trappes (N)", "Vanves – Malakoff", "Versailles – Chantiers (N)", "Villepreux – Les Clayes", "Villiers – Neauphle – Pontchartrain", "Viroflay – Rive Gauche (N)"],
            "P" => ["Champbenoist‑Poigny", "Changis‑Saint‑Jean", "Château‑Thierry", "Chelles–Gournay", "Chézy‑sur‑Marne", "Coulommiers", "Crécy‑la‑Chapelle", "Crouy‑sur‑Ourcq", "Esbly", "Faremoutiers–Pommeuse", "Guérard–La Celle‑sur‑Morin", "Isles‑Armentières‑Congis", "La Ferté‑Milon", "La Ferté‑sous‑Jouarre", "Lagny–Thorigny", "Lizy‑sur‑Ourcq", "Longueville", "Males‑en‑Brie", "Mareuil‑sur‑Ourcq", "Meaux", "Mormant", "Mortcerf", "Mouroux", "Nangis", "Nanteuil‑Saâcy", "Nogent‑l’Artaud‑Charly", "Paris–Est", "Provins", "Sainte‑Colombe‑Septveilles", "Tournan", "Trilport", "Vaires–Torcy", "Verneuil‑l’Étang", "Villiers‑Montbarbin (Crécy‑la‑Chapelle)"],
            "R" => ["Bagneaux-sur-Loing", "Bois-le-Roi", "Bourron-Marlotte – Grez", "Brunoy", "Boussy-Saint-Antoine", "Cesson", "Champagne-sur-Seine", "Chartrettes", "Combs-la-Ville – Quincy", "Créteil-Pompadour", "Dordives", "Ferrières – Fontenay", "Fontaine-le-Port", "Fontainebleau – Avon", "Héricy", "La Grande-Paroisse", "Le Mée-sur-Seine", "Le Vert de Maisons", "Lieusaint – Moissy", "Livry-sur-Seine", "Maisons-Alfort – Alfortville", "Melun", "Montargis", "Montereau", "Montgeron – Crosne", "Moret – Veneux-les-Sablons", "Nemours – Saint-Pierre", "Paris-Gare de Lyon (R)", "Saint-Mammès", "Savigny-le-Temple – Nandy", "Souppes – Château-Landon", "Thomery", "Villeneuve-Saint-Georges", "Vulaines-sur-Seine – Samoreau", "Yerres"],
            "U" => ["Chaville-Rive-Droite (U)", "Issy – Val de Seine", "La Défense (U)", "La Verrière (U)", "Marnes-la-Coquette", "Pont du Garigliano", "Puteaux (U)", "Saint-Cloud (U)", "Saint-Quentin-en-Yvelines (U)", "Sèvres – Ville d’Avray (U)", "Suresnes-Mont-Valérien (U)", "Trappes (U)", "Versailles-Chantiers (U)"],
        ];

        foreach ($allGaresData as $nomLigne => $gares) {
            $ligne = LigneRer::where('name', $nomLigne)->first();
            if ($ligne) {
                foreach ($gares as $nomGare) {
                    Gare::firstOrCreate(
                        ['name' => $nomGare],
                        ['ligne_rer_id' => $ligne->id]
                    );
                }
            }
        }
    }
}